# Generated by Django 3.2.7 on 2021-09-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
